# Generated by Django 4.2.2 on 2023-11-09 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('numero_cas', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('controlado', models.BooleanField()),
                ('codigo_sap', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecutivo_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('lote_proveedor', models.CharField(max_length=20)),
                ('concentracion', models.CharField(max_length=10)),
                ('cantidad', models.FloatField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.estado')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.fabricante')),
                ('numero_cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.base')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.proveedor')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.unidad')),
                ('unidades_recibidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.orden')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.reactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('fecha_consumo', models.DateField(auto_now_add=True)),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.reactivo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('año', models.CharField(max_length=4)),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.reactivo')),
            ],
        ),
        migrations.AddField(
            model_name='base',
            name='codigo_reactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.codigo'),
        ),
        migrations.AddField(
            model_name='base',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.fase'),
        ),
        migrations.AddField(
            model_name='base',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.ubicacion'),
        ),
    ]
