# Generated by Django 4.2.2 on 2023-07-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivo',
            name='consecutivo_ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
