# Generated by Django 4.2.2 on 2023-07-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reactivos', '0003_consumo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_reactivos.unidad'),
            preserve_default=False,
        ),
    ]
